// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaCHeJxK11L7uz73sJqSIoUZrHbNKbAp8',
    appId: '1:1076191631945:web:89949543c4785a478ebd98',
    messagingSenderId: '1076191631945',
    projectId: 'checkout-a367a',
    authDomain: 'checkout-a367a.firebaseapp.com',
    storageBucket: 'checkout-a367a.appspot.com',
    measurementId: 'G-MHZ6VJ6WVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2n5PCvXgn1iTRKd5WMaBMYa_M7Xat-E',
    appId: '1:1076191631945:android:b87fdb34c256a1ff8ebd98',
    messagingSenderId: '1076191631945',
    projectId: 'checkout-a367a',
    storageBucket: 'checkout-a367a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2AtX0dYR5mJP2phoczCEE7e1bJAv5VSA',
    appId: '1:1076191631945:ios:3338e8a0ec7688018ebd98',
    messagingSenderId: '1076191631945',
    projectId: 'checkout-a367a',
    storageBucket: 'checkout-a367a.appspot.com',
    iosClientId: '1076191631945-g45dpks50p7b8pcgodthmmi1r8doe5g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.order2eat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2AtX0dYR5mJP2phoczCEE7e1bJAv5VSA',
    appId: '1:1076191631945:ios:3338e8a0ec7688018ebd98',
    messagingSenderId: '1076191631945',
    projectId: 'checkout-a367a',
    storageBucket: 'checkout-a367a.appspot.com',
    iosClientId: '1076191631945-g45dpks50p7b8pcgodthmmi1r8doe5g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.order2eat',
  );
}
